/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GameLogic_JoystickReader */

#ifndef _Included_GameLogic_JoystickReader
#define _Included_GameLogic_JoystickReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GameLogic_JoystickReader
 * Method:    createJoystick
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_GameLogic_JoystickReader_createJoystick
  (JNIEnv *, jobject, jint);

/*
 * Class:     GameLogic_JoystickReader
 * Method:    destroyJoystick
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_GameLogic_JoystickReader_destroyJoystick
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GameLogic_JoystickReader
 * Method:    readJoystick
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GameLogic_JoystickReader_readJoystick
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
